using System;
using System.Collections.Generic;
using System.Text;

namespace csharp.Enum

{
    public class KnownCostCode
    {
        public IList<CostCodes> Values { get; set; }

        public KnownCostCode()
        {
            Values = new List<CostCodes>();
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_010, CostCodes.Languages.en, "Buildings-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_020, CostCodes.Languages.en, "Buildings-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_030, CostCodes.Languages.en, "Buildings-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_040, CostCodes.Languages.en, "Buildings-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_050, CostCodes.Languages.en, "Buildings-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_060, CostCodes.Languages.en, "Buildings-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_070, CostCodes.Languages.en, "Buildings-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_080, CostCodes.Languages.en, "Buildings-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_090, CostCodes.Languages.en, "Buildings-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_CC_095, CostCodes.Languages.en, "Buildings-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_AC_010, CostCodes.Languages.en, "Buildings-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_AC_020, CostCodes.Languages.en, "Buildings-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_AC_030, CostCodes.Languages.en, "Buildings-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_AC_040, CostCodes.Languages.en, "Buildings-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_SC_010, CostCodes.Languages.en, "Buildings-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.BD_SC_020, CostCodes.Languages.en, "Buildings-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_010, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_020, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_030, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_040, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_050, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_060, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_070, CostCodes.Languages.en, "Roads and motorways-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_080, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_090, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_CC_095, CostCodes.Languages.en, "Roads and motorways-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_AC_010, CostCodes.Languages.en, "Roads and motorways-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_AC_020, CostCodes.Languages.en, "Roads and motorways-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_AC_030, CostCodes.Languages.en, "Roads and motorways-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_AC_040, CostCodes.Languages.en, "Roads and motorways-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_SC_010, CostCodes.Languages.en, "Roads and motorways-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.RM_SC_020, CostCodes.Languages.en, "Roads and motorways-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_010, CostCodes.Languages.en, "Railways-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_020, CostCodes.Languages.en, "Railways-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_030, CostCodes.Languages.en, "Railways-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_040, CostCodes.Languages.en, "Railways-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_050, CostCodes.Languages.en, "Railways-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_060, CostCodes.Languages.en, "Railways-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_070, CostCodes.Languages.en, "Railways-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_080, CostCodes.Languages.en, "Railways-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_090, CostCodes.Languages.en, "Railways-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_CC_095, CostCodes.Languages.en, "Railways-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_AC_010, CostCodes.Languages.en, "Railways-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_AC_020, CostCodes.Languages.en, "Railways-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_AC_030, CostCodes.Languages.en, "Railways-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_AC_040, CostCodes.Languages.en, "Railways-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_SC_010, CostCodes.Languages.en, "Railways-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.RW_SC_020, CostCodes.Languages.en, "Railways-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_010, CostCodes.Languages.en, "Bridges-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_020, CostCodes.Languages.en, "Bridges-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_030, CostCodes.Languages.en, "Bridges-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_040, CostCodes.Languages.en, "Bridges-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_050, CostCodes.Languages.en, "Bridges-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_060, CostCodes.Languages.en, "Bridges-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_070, CostCodes.Languages.en, "Bridges-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_080, CostCodes.Languages.en, "Bridges-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_090, CostCodes.Languages.en, "Bridges-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_CC_095, CostCodes.Languages.en, "Bridges-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_AC_010, CostCodes.Languages.en, "Bridges-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_AC_020, CostCodes.Languages.en, "Bridges-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_AC_030, CostCodes.Languages.en, "Bridges-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_AC_040, CostCodes.Languages.en, "Bridges-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_SC_010, CostCodes.Languages.en, "Bridges-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.BG_SC_020, CostCodes.Languages.en, "Bridges-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_010, CostCodes.Languages.en, "Tunnels-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_020, CostCodes.Languages.en, "Tunnels-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_030, CostCodes.Languages.en, "Tunnels-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_040, CostCodes.Languages.en, "Tunnels-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_050, CostCodes.Languages.en, "Tunnels-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_060, CostCodes.Languages.en, "Tunnels-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_070, CostCodes.Languages.en, "Tunnels-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_080, CostCodes.Languages.en, "Tunnels-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_090, CostCodes.Languages.en, "Tunnels-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_CC_095, CostCodes.Languages.en, "Tunnels-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_AC_010, CostCodes.Languages.en, "Tunnels-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_AC_020, CostCodes.Languages.en, "Tunnels-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_AC_030, CostCodes.Languages.en, "Tunnels-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_AC_040, CostCodes.Languages.en, "Tunnels-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_SC_010, CostCodes.Languages.en, "Tunnels-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.TN_SC_020, CostCodes.Languages.en, "Tunnels-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_010, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_020, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_030, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_040, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_050, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_060, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_070, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_080, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_090, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_CC_095, CostCodes.Languages.en, "Waste water treatment works-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_AC_010, CostCodes.Languages.en, "Waste water treatment works-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_AC_020, CostCodes.Languages.en, "Waste water treatment works-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_AC_030, CostCodes.Languages.en, "Waste water treatment works-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_AC_040, CostCodes.Languages.en, "Waste water treatment works-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_SC_010, CostCodes.Languages.en, "Waste water treatment works-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.WW_SC_020, CostCodes.Languages.en, "Waste water treatment works-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_010, CostCodes.Languages.en, "Water treatment works-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_020, CostCodes.Languages.en, "Water treatment works-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_030, CostCodes.Languages.en, "Water treatment works-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_040, CostCodes.Languages.en, "Water treatment works-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_050, CostCodes.Languages.en, "Water treatment works-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_060, CostCodes.Languages.en, "Water treatment works-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_070, CostCodes.Languages.en, "Water treatment works-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_080, CostCodes.Languages.en, "Water treatment works-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_090, CostCodes.Languages.en, "Water treatment works-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_CC_095, CostCodes.Languages.en, "Water treatment works-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_AC_010, CostCodes.Languages.en, "Water treatment works-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_AC_020, CostCodes.Languages.en, "Water treatment works-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_AC_030, CostCodes.Languages.en, "Water treatment works-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_AC_040, CostCodes.Languages.en, "Water treatment works-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_SC_010, CostCodes.Languages.en, "Water treatment works-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.WT_SC_020, CostCodes.Languages.en, "Water treatment works-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_010, CostCodes.Languages.en, "Treatments-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_020, CostCodes.Languages.en, "Treatments-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_030, CostCodes.Languages.en, "Treatments-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_040, CostCodes.Languages.en, "Treatments-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_050, CostCodes.Languages.en, "Treatments-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_060, CostCodes.Languages.en, "Treatments-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_070, CostCodes.Languages.en, "Treatments-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_080, CostCodes.Languages.en, "Treatments-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_090, CostCodes.Languages.en, "Treatments-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_CC_095, CostCodes.Languages.en, "Treatments-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_AC_010, CostCodes.Languages.en, "Treatments-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_AC_020, CostCodes.Languages.en, "Treatments-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_AC_030, CostCodes.Languages.en, "Treatments-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_AC_040, CostCodes.Languages.en, "Treatments-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_SC_010, CostCodes.Languages.en, "Treatments-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.PL_SC_020, CostCodes.Languages.en, "Treatments-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_010, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_020, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_030, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_040, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_050, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_060, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_070, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_080, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_090, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_CC_095, CostCodes.Languages.en, "Wells and boreholes-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_AC_010, CostCodes.Languages.en, "Wells and boreholes-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_AC_020, CostCodes.Languages.en, "Wells and boreholes-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_AC_030, CostCodes.Languages.en, "Wells and boreholes-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_AC_040, CostCodes.Languages.en, "Wells and boreholes-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_SC_010, CostCodes.Languages.en, "Wells and boreholes-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.WB_SC_020, CostCodes.Languages.en, "Wells and boreholes-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_010, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_020, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_030, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_040, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_050, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_060, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_070, CostCodes.Languages.en, "Power-generating plants-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_080, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_090, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_CC_095, CostCodes.Languages.en, "Power-generating plants-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_AC_010, CostCodes.Languages.en, "Power-generating plants-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_AC_020, CostCodes.Languages.en, "Power-generating plants-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_AC_030, CostCodes.Languages.en, "Power-generating plants-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_AC_040, CostCodes.Languages.en, "Power-generating plants-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_SC_010, CostCodes.Languages.en, "Power-generating plants-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.PG_SC_020, CostCodes.Languages.en, "Power-generating plants-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_010, CostCodes.Languages.en, "Chemical plants-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_020, CostCodes.Languages.en, "Chemical plants-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_030, CostCodes.Languages.en, "Chemical plants-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_040, CostCodes.Languages.en, "Chemical plants-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_050, CostCodes.Languages.en, "Chemical plants-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_060, CostCodes.Languages.en, "Chemical plants-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_070, CostCodes.Languages.en, "Chemical plants-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_080, CostCodes.Languages.en, "Chemical plants-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_090, CostCodes.Languages.en, "Chemical plants-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_CC_095, CostCodes.Languages.en, "Chemical plants-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_AC_010, CostCodes.Languages.en, "Chemical plants-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_AC_020, CostCodes.Languages.en, "Chemical plants-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_AC_030, CostCodes.Languages.en, "Chemical plants-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_AC_040, CostCodes.Languages.en, "Chemical plants-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_SC_010, CostCodes.Languages.en, "Chemical plants-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.CP_SC_020, CostCodes.Languages.en, "Chemical plants-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_010, CostCodes.Languages.en, "Refineries-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_020, CostCodes.Languages.en, "Refineries-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_030, CostCodes.Languages.en, "Refineries-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_040, CostCodes.Languages.en, "Refineries-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_050, CostCodes.Languages.en, "Refineries-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_060, CostCodes.Languages.en, "Refineries-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_070, CostCodes.Languages.en, "Refineries-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_080, CostCodes.Languages.en, "Refineries-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_090, CostCodes.Languages.en, "Refineries-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_CC_095, CostCodes.Languages.en, "Refineries-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_AC_010, CostCodes.Languages.en, "Refineries-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_AC_020, CostCodes.Languages.en, "Refineries-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_AC_030, CostCodes.Languages.en, "Refineries-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_AC_040, CostCodes.Languages.en, "Refineries-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_SC_010, CostCodes.Languages.en, "Refineries-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.RF_SC_020, CostCodes.Languages.en, "Refineries-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_010, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_020, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_030, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_040, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_050, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_060, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_070, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_080, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_090, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_CC_095, CostCodes.Languages.en, "Dams and reservoirs-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_AC_010, CostCodes.Languages.en, "Dams and reservoirs-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_AC_020, CostCodes.Languages.en, "Dams and reservoirs-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_AC_030, CostCodes.Languages.en, "Dams and reservoirs-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_AC_040, CostCodes.Languages.en, "Dams and reservoirs-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_SC_010, CostCodes.Languages.en, "Dams and reservoirs-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.DR_SC_020, CostCodes.Languages.en, "Dams and reservoirs-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_010, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Demolition, site preparation and formation"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_020, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Substructure"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_030, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Structure"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_040, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Architectural works | Non-structural works"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_050, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Services and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_060, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Surface and underground drainage"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_070, CostCodes.Languages.en, "Mines and quarries-Construction Costs-External and ancillary works"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_080, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Preliminaries | Constructor's site overheads | general requirements"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_090, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_CC_095, CostCodes.Languages.en, "Mines and quarries-Construction Costs-Taxes and Levies"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_AC_010, CostCodes.Languages.en, "Mines and quarries-Associated Costs (each including taxes)-Work and utilities off-site"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_AC_020, CostCodes.Languages.en, "Mines and quarries-Associated Costs (each including taxes)-Post-completion loose furniture, fittings and equipment"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_AC_030, CostCodes.Languages.en, "Mines and quarries-Associated Costs (each including taxes)-Construction-related consultants and supervision"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_AC_040, CostCodes.Languages.en, "Mines and quarries-Associated Costs (each including taxes)-Risk Allowances"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_SC_010, CostCodes.Languages.en, "Mines and quarries-Site Acquisition and Client's Other Costs (each including risks and taxes)-Site acquisition"));
            Values.Add(new CostCodes(CostCodes.Codes.MQ_SC_020, CostCodes.Languages.en, "Mines and quarries-Site Acquisition and Client's Other Costs (each including risks and taxes)-Client's administrative, finance, legal and marketing expenses"));
        }
    }   
}
